Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.define "mongodb" do |mongodb|
    mongodb.vm.box = "ubuntu/bionic64"
	mongodb.vm.network "private_network", ip: "192.168.50.50"
	mongodb.vm.network "forwarded_port", guest: 27017, host: 27017
	mongodb.vm.hostname = "mongodb"
	mongodb.vm.provision "shell", path: "mongodb/bootstrap.sh", run: "always"
  end
end